security:
    # Password hashers
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    # User providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email  # Utiliser email pour l'authentification

    firewalls:
        # Développement
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Authentification par formulaire JSON
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check  # Route pour la validation des identifiants
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # API firewall avec JWT
        api:
            pattern: ^/api
            stateless: true
            jwt: ~  # Utilisation de JWT pour l'authentification des autres routes de l'API

    # Access control
    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }  # La route login est publique
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }  # Les autres routes nécessitent une authentification
